version: "3"

services:
  postgres:
    container_name: db
    build:
      context: ./.docker/
      dockerfile: ./postgres.dockerfile
    environment:
      - POSTGRES_DB=ngts_iue_dmd
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
    ports:
      - "5432:5432"
    cap_add:
      - SYS_NICE
    networks:
      - ngts_iue_dmd
  php:
    container_name: api
    build:
      context: ./.docker/
      dockerfile: ./php.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./api:/var/www/api"
    depends_on:
      - "postgres"
    networks:
      - ngts_iue_dmd
networks:
  ngts_iue_dmd:
    driver: bridge
